### ISSUE TITLE
Environment Variables Not Being Applied in interactsh-web

### ISSUE THREAD

**Issue by dam2452** [projectdiscovery/interactsh-web#172]
#### Description

The environment variables provided to the `interactsh-web` container (e.g., `REACT_APP_HOST`, `REACT_APP_TOKEN`) are not automatically applied to the web interface. Despite being set via `docker run` as `-e` options, these variables are not used by the application, and the user is required to manually input them in the "Custom Host" section of the GUI.

#### Steps to Reproduce

1. Run the `interactsh-web` Docker container with the following command:
   ```bash
   docker run -it -p 3000:3000 \
     -e REACT_APP_HOST="example.com" \
     -e REACT_APP_TOKEN="123456789abcdef123456789abcdef123456789abcdef123456789abcdef" \
     projectdiscovery/interactsh-web
   ```

2. Open the web interface in your browser at `http://localhost:3000`.

3. Attempt to use the application without entering any configuration manually.

#### Expected Behavior

The application should automatically use the provided environment variables:
- `REACT_APP_HOST="example.com"`
- `REACT_APP_TOKEN="123456789abcdef123456789abcdef123456789abcdef123456789abcdef"`

These values should be pre-filled or directly applied without the need for manual input in the "Custom Host" field in the GUI.

#### Actual Behavior

The application does not apply the provided environment variables. Instead:
- The user is required to manually input the `REACT_APP_HOST` and `REACT_APP_TOKEN` values in the "Custom Host" section for the application to function correctly.

#### Environment

- **Docker Image**: `projectdiscovery/interactsh-web`
- **Version**: `latest`
- **Host System**: Windows 11 (Docker Desktop)
- **Browser**: Chrome

**Comment by ssqlone** [comment]
Their Docker image uses a development instance instead of a built version, which seems quite unusual, and I'm not sure why they chose to do that.

You can build and deploy your own image, or use one that I have already built.

The built image works perfectly in a self-hosted setup. It supports both CIDN and CIDL while using only 6 MB of RAM, compared to the 1500 MB of their from HUB :) . You can also build your own image and replace it with my link. 

docker-compose for local:
```
services:
  interactsh:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: interactsh:latest
    container_name: interactsh
    ports:
      - 127.0.0.1:80:80
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Baku
    volumes:
      - './interactsh:/app/data'
networks:
  proxy:
```

Dockerfile: 
```
# Use a minimal Nginx image
FROM nginx:alpine

# Set the working directory inside the container
WORKDIR /usr/share/nginx/html

# Install curl and unzip to download the web release
RUN apk update && \
    apk add --no-cache curl unzip

# Download and extract the web release
RUN curl -L https://github.com/ssqlone/interactsh-web/releases/download/Latest/interactsh.zip -o interactsh.zip && \
    unzip -o interactsh.zip && \
    mv interactsh/* ./ && \
    rm interactsh.zip

# Expose port 80 for web access
EXPOSE 80

# Command to run the Nginx server (default Nginx configuration is fine)
CMD ["nginx", "-g", "daemon off;"]
```

Usage:
```
docker compose up --build
```
